apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-svc
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: "3306"
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
