apiVersion: v1
kind: Service
metadata:
  labels:
    app: moodle
  name: moodle-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      name: "8080"
      protocol: TCP
      targetPort: 8080
    - port: 8443
      name: "8443"
      protocol: TCP
      targetPort: 8443
  selector:
    app: moodle
